#pragma once
#include <memory>
#include <chrono>
#include <string>
#include <sstream>
#include <array>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <filesystem>
#include <iostream>
#include <fstream>
#include <regex>
#include <fstream>
#include <stack>
#include <algorithm>
#include <cassert>
#include <functional>
#include <thread>
#include <mutex>
#include <future>

#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_KEYSTATE_BASED_INPUT

#include <stb_image.h>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <nuklear.h>
#include <demo/glfw_opengl3/nuklear_glfw_gl3.h>
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/string_cast.hpp>
#include <glm/gtx/projection.hpp>
#include <glm/gtx/wrap.hpp>
#include <glm/gtx/matrix_decompose.hpp>
#include <jzon/Jzon.h>
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>