#pragma once
#include <memory>
#include <chrono>
#include <string>
#include <string_view>
#include <sstream>
#include <array>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <filesystem>
#include <iostream>
#include <fstream>
#include <regex>
#include <fstream>
#include <stack>
#include <algorithm>
#include <cassert>
#include <functional>
#include <thread>
#include <mutex>
#include <future>
#include <limits>
#include <cctype>
#include <stdio.h>
#include <stdarg.h>

#include <stb_image.h>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#define GLM_FORCE_SWIZZLE
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/string_cast.hpp>
#include <glm/gtx/projection.hpp>
#include <glm/gtx/wrap.hpp>
#include <glm/gtx/matrix_decompose.hpp>
#include <jzon/Jzon.h>
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
#include <lua.hpp>
#define BT_USE_DOUBLE_PRECISION
#include <btBulletCollisionCommon.h>
#include <btBulletDynamicsCommon.h>