#pragma once

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/string_cast.hpp>
#include <glm/gtx/projection.hpp>
#include <glm/gtx/wrap.hpp>
#include <jzon/Jzon.h>
#include <imgui/imgui.h>
#include <imgui/imgui_impl_glfw_gl3.h>

#include "helpers/helpers.h"
#include "buffer/vectors.h"
#include "other/enums.h"
#include "application/window.h"
#include "application/application.h"
#include "other/glerror.h"
#include "object/object.h"
#include "object/resource.h"
#include "other/glstatic.h"
#include "buffer/vertexBuffer.h"
#include "buffer/vertexArray.h"
#include "shader/shaderCompileException.h"
#include "shader/shaderStage.h"
#include "shader/shaderProgram.h"
#include "shader/shaderLoader.h"
#include "query/query.h"
#include "query/gpuStopwatch.h"
#include "helpers/guiHelper.h"
#include "texture/textureBase.h"
#include "texture/textureLoaderHelpers.h"
#include "texture/texture2D/texture2D.h"
#include "texture/texture2D/texture2DLoader.h"
#include "texture/texture2DArray/texture2DArray.h"
#include "texture/texture2DArray/texture2DArrayLoader.h"
#include "texture/textureCube/textureCube.h"
#include "texture/textureCube/textureCubeLoader.h"
#include "texture/texture3D/texture3D.h"
#include "shader/material.h"
#include "framebuffer/framebuffer.h"
#include "framebuffer/renderTarget.h"
#include "helpers/math3D.h"
#include "components/transform.h"
#include "components/camera.h"
#include "mesh/meshBase.h"
#include "mesh/modelMesh.h"
#include "mesh/screenQuadMesh.h"
#include "mesh/coordBasisMesh.h"
#include "mesh/terrainMesh.h"
#include "components/terrain.h"
#include "components/clouds.h"
#include "pipelines/deferredPBRPipeline.h"
